spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/store
    username: comp5348
    password: changeme
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
#      jakarta.persistence.schema-generation.database.action: none
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    clean-disabled: true

  kafka:
    bootstrap-servers: localhost:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: com.example.store.**
        spring.json.use.type.headers: true
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
    listener:
      ack-mode: record

---
app:
  kafka:
    partitions: 3
    replicas: 1
    topics:
      orders: orders
      inventory: inventory
      payments: payments
      shipping: shipping
      notifications: notifications

  endpoints:
    bank: http://localhost:8081
    delivery-co: http://localhost:8082
    email: http://localhost:8083

  simulation:
    payments-success-rate: 0.8
    shipping-success-rate: 0.85
    notify-success-rate: 0.95

  delivery:
    # Shared secret for DeliveryCo webhook auth (must match DeliveryCo config)
    secret: change-me
