spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: yasmineibrahim
    password: yibr2004
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false

  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: store-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8080

jwt:
  secretKey: ads9f6askj3h4k1hf86asdfiahkjh34a789s6df89ayshkjh3jkh786adsf78ay

deploy:
  env: development

default:
  admin:
    email: admin@example.com
    password: supersaiya

kafka:
  topics:
    orders: "orders"
    inventory: "inventory"
    payments: "payments"
    shipping: "shipping"
    notifications: "notifications"
  partitions: 1
  replicas: 1

app:
  endpoints:
    bank: http://localhost:8081
    delivery-co: http://localhost:8082
    email: http://localhost:8083
  simulation:
    payments-success-rate: 0.8
    shipping-success-rate: 0.85
    notify-success-rate: 0.95
  delivery:
    secret: change-me