services:
  postgres:
    image: postgres:15-alpine
    container_name: comp5348-postgres
    environment:
      POSTGRES_DB: comp5348
      POSTGRES_USER: comp5348
      POSTGRES_PASSWORD: changeme
    ports:
      - "15432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: comp5348-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@comp5348.com
      PGADMIN_DEFAULT_PASSWORD: changeme
    ports:
      - "5050:80"
    depends_on:
      - postgres
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: comp5348-kafka-ui
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "6060:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      DYNAMIC_CONFIG_ENABLED: "true"

#volumes:
#  postgres-data:
#  pgadmin-data: